/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EstimateRouteImport } from './routes/estimate'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FieldsRouteImport } from './routes/fields'
import { Route as HowToRouteImport } from './routes/how-to'
import { Route as IphoneRouteImport } from './routes/iphone'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TaxRouteImport } from './routes/tax'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UseCasesRouteImport } from './routes/use-cases'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateRoute = EstimateRouteImport.update({
  id: '/estimate',
  path: '/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldsRoute = FieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToRoute = HowToRouteImport.update({
  id: '/how-to',
  path: '/how-to',
  getParentRoute: () => rootRouteImport,
} as any)
const IphoneRoute = IphoneRouteImport.update({
  id: '/iphone',
  path: '/iphone',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxRoute = TaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/estimate': typeof EstimateRoute
  '/faq': typeof FaqRoute
  '/fields': typeof FieldsRoute
  '/how-to': typeof HowToRoute
  '/iphone': typeof IphoneRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tax': typeof TaxRoute
  '/terms': typeof TermsRoute
  '/use-cases': typeof UseCasesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/estimate': typeof EstimateRoute
  '/faq': typeof FaqRoute
  '/fields': typeof FieldsRoute
  '/how-to': typeof HowToRoute
  '/iphone': typeof IphoneRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tax': typeof TaxRoute
  '/terms': typeof TermsRoute
  '/use-cases': typeof UseCasesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/estimate': typeof EstimateRoute
  '/faq': typeof FaqRoute
  '/fields': typeof FieldsRoute
  '/how-to': typeof HowToRoute
  '/iphone': typeof IphoneRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tax': typeof TaxRoute
  '/terms': typeof TermsRoute
  '/use-cases': typeof UseCasesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/estimate'
    | '/faq'
    | '/fields'
    | '/how-to'
    | '/iphone'
    | '/privacy'
    | '/sitemap.xml'
    | '/tax'
    | '/terms'
    | '/use-cases'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/estimate'
    | '/faq'
    | '/fields'
    | '/how-to'
    | '/iphone'
    | '/privacy'
    | '/sitemap.xml'
    | '/tax'
    | '/terms'
    | '/use-cases'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/estimate'
    | '/faq'
    | '/fields'
    | '/how-to'
    | '/iphone'
    | '/privacy'
    | '/sitemap.xml'
    | '/tax'
    | '/terms'
    | '/use-cases'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EstimateRoute: typeof EstimateRoute
  FaqRoute: typeof FaqRoute
  FieldsRoute: typeof FieldsRoute
  HowToRoute: typeof HowToRoute
  IphoneRoute: typeof IphoneRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TaxRoute: typeof TaxRoute
  TermsRoute: typeof TermsRoute
  UseCasesRoute: typeof UseCasesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate': {
      id: '/estimate'
      path: '/estimate'
      fullPath: '/estimate'
      preLoaderRoute: typeof EstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fields': {
      id: '/fields'
      path: '/fields'
      fullPath: '/fields'
      preLoaderRoute: typeof FieldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to': {
      id: '/how-to'
      path: '/how-to'
      fullPath: '/how-to'
      preLoaderRoute: typeof HowToRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iphone': {
      id: '/iphone'
      path: '/iphone'
      fullPath: '/iphone'
      preLoaderRoute: typeof IphoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax': {
      id: '/tax'
      path: '/tax'
      fullPath: '/tax'
      preLoaderRoute: typeof TaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EstimateRoute: EstimateRoute,
  FaqRoute: FaqRoute,
  FieldsRoute: FieldsRoute,
  HowToRoute: HowToRoute,
  IphoneRoute: IphoneRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TaxRoute: TaxRoute,
  TermsRoute: TermsRoute,
  UseCasesRoute: UseCasesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
